---
- name: Create build directory
  file: path='{{build_dir}}' state=directory

- name: Copy template file to build
  template: src='{{docker_template}}' dest='{{build_dir}}'

- name: Build docker image
  shell : packer build '{{docker_template}}'
  args:
    chdir: '{{build_dir}}'

- name: Docker repo login
  shell: docker login --username {{repo_username}} --password {{repo_password}}

- name: Push image
  docker_image:
    name: '{{docker_image_name}}'
    repository: '{{docker_repo}}'
    tag: '{{tag}}'
    push: yes
